artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://goo.gl/8hY5ER
  local_data_file: artifacts/data_ingestion/UrbanSound8K.tar
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FOLDERS: ["artifacts/data_ingestion/UrbanSound8K/audio","artifacts/data_ingestion/UrbanSound8K/metadata"]



data_transformation:
  root_dir: artifacts/data_transformation
  audio_data_path: artifacts/data_ingestion/UrbanSound8K/audio
  meta_data_path: artifacts/data_ingestion/UrbanSound8K/metadata/UrbanSound8K.csv


model_trainer:
  root_dir: artifacts/model_trainer
  preprocessed_data_path : artifacts/data_transformation/preprocessed_data.json
  trained_model_path: artifacts/model_trainer


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/preprocessed_data.json
  model_path: artifacts/model_trainer/model.hdf5
  metric_file_name: artifacts/model_evaluation/metrics.csv
