artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://goo.gl/8hY5ER
  local_data_file: artifacts/data_ingestion/UrbanSound8K.tar
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FOLDERS: ["artifacts/data_ingestion/UrbanSound8K/audio","artifacts/data_ingestion/UrbanSound8K/metadata"]



data_transformation:
  root_dir: artifacts/data_transformation
  audio_data_path: artifacts/data_ingestion/UrbanSound8K/audio
  meta_data_path: artifacts/data_ingestion/UrbanSound8K/metadata/UrbanSound8K.csv




# prepare_base_model:
#   root_dir: artifacts/prepare_base_model
#   base_model_path: artifacts/prepare_base_model/base_model.h5
#   updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5




# training:
#   root_dir: artifacts/training
#   trained_model_path: artifacts/training/model.h5
